### ISSUE TITLE
Code runs for a while before warning of format constraints

### ISSUE THREAD

**Issue by dylanbmorgan** [HetSys/SpinDec2#22]
If incorrect variables sizes are specified in the input file, the code runs for a while before stopping and outputting the error. I think it's better (if possible) if the code exits immediately after starting so as not to waste CPU time, etc.

**Comment by ShufflerBardOnTheEdge** [comment]
For which variables in the input file does this happen

**Comment by dylanbmorgan** [comment]
I was trying to change the grid size to profile with different grid sizes in serial

**Comment by dylanbmorgan** [comment]
It was the thing I messaged you about yesterday. I tried it with 500 first then 250 and both times it errored

**Comment by dylanbmorgan** [comment]
- [ ] Re-write netcdf to write a checkpoint file every timestep to circumvent memory issues

**Comment by ShufflerBardOnTheEdge** [comment]
The checkpointing system did not need to be changed, the code will now incrementally write to the output file and no longer stores more than 3 frames in memory.
