### ISSUE TITLE
Visualisation of Output Data 

### ISSUE THREAD

**Issue by dylanbmorgan** [HetSys/SpinDec2#4]
- [x] Basic plots
- [x] Animation

**Comment by dylanbmorgan** [comment]
@gosling123 Can this be closed yet? Sounds/looks to me like the basic plots are done but the animations need to be sped up?

**Comment by gosling123** [comment]
Yeah, I’m pretty sure the specification has been met and a bit more. Just a case of making it run a bit faster and some minor presentation tweaks

**Comment by dylanbmorgan** [comment]
- [ ] Increase animation performance

Do you mind just ticking the box and closing the issue after the changes have been pushed to main @gosling123

**Comment by gosling123** [comment]
Yeah, I'm aiming to have it done by Monday evening. Don't think it'll take that long but seems a sensible deadline

**Comment by gosling123** [comment]
- [ ] Add option to save animations/plots or just print to screen

**Comment by gosling123** [comment]
- [ ] change bounds plot

**Comment by gosling123** [comment]
- [ ] fix time average issue at last point in free energy

**Comment by gosling123** [comment]
Yeah, I’m pretty sure the specification has been met and a bit more. Just a case of making it run a bit faster and some minor presentation tweaks
________________________________
