### ISSUE TITLE
Specification Extension Tasks

### ISSUE THREAD

**Issue by dylanbmorgan** [HetSys/SpinDec2#9]
Add functionality for the following specification extension tasks:

- [x] Checkpointing 
- [x] User-defined polynomials in input

**Comment by ShufflerBardOnTheEdge** [comment]
The automatic check-pointing may not be required. It would require more involved code and possible a reasonable amount of computation time. Currently automatic check-pointing does not seem like it would have much of an impact and so I will not implement it unless it seems necessary.

**Comment by dylanbmorgan** [comment]
@ShufflerBardOnTheEdge Sure thing, so how does it work now? Does the user just define after how many steps the checkpointing file will be written?

**Comment by ShufflerBardOnTheEdge** [comment]
Yea that is how it currently works
